# Generated by Django 4.1.1 on 2022-10-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pincode',
            field=models.IntegerField(max_length=15),
        ),
    ]
