# Generated by Django 4.1.1 on 2022-10-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
