# Generated by Django 4.1.1 on 2022-10-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.TextField(max_length=50),
        ),
    ]
