# Generated by Django 4.1.1 on 2022-10-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_appointment_patient_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='endtime',
            field=models.IntegerField(default='00'),
        ),
    ]
