# Generated by Django 4.1.1 on 2022-10-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_appointment_endtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('profile', models.ImageField(default='default.jpg', upload_to='')),
                ('lastname', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('1', 'Doctor'), ('2', 'Patient')], default='2', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.TextField(),
        ),
    ]
