# Generated by Django 4.1.1 on 2022-10-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_addperson_delete_doctor_delete_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addperson',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
