# Generated by Django 4.1.1 on 2022-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_addperson_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addperson',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
