# Generated by Django 4.1.1 on 2022-10-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_addperson_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addperson',
            old_name='address',
            new_name='addressline1',
        ),
        migrations.AddField(
            model_name='addperson',
            name='city',
            field=models.CharField(default='Ghaziabad', max_length=50),
        ),
        migrations.AddField(
            model_name='addperson',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addperson',
            name='state',
            field=models.CharField(default='UP', max_length=50),
        ),
    ]
